- name: Configure web servers
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy simple HTML page
      copy:
        content: "<h1>Hello from Terraform + Ansible 🚀</h1>"
        dest: /usr/share/nginx/html/index.html
